-- Insertion des produits initiaux pour FAITH DECOR
USE faith_decor;

-- Vider la table avant insertion pour repartir sur une base propre
DELETE FROM products;
ALTER TABLE products AUTO_INCREMENT = 1;

INSERT INTO products (id, title, category, category_label, rental_price, promo_percentage, image_url, description, details, is_popular) VALUES
(1, 'Kaftan de Mariée d\'Or', 'tenues', 'Tenue Traditionnelle', 100000.00, NULL, 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=800', 'Velours de soie d\'exception orné de broderies fines métalliques faites à la main par nos artisans maîtres doreurs.', 'Inclus : Kaftan principal, sur-robe en mousseline fine et ceinture assortie. Tailles disponibles : S, M, L.', 1),
(2, 'Parure de Perles & Or', 'bijoux', 'Bijoux & Parures', 50000.00, NULL, 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=800', 'Collier plastron et boucles d\'oreilles pendantes en perles nacrées et laiton doré à l\'or fin.', 'Finition hypoallergénique, fermoir sécurisé. Parfait pour sublimer un port de tête royal.', 1),
(3, 'Robe Émeraude Royale', 'tenues', 'Robe de Soirée', 80000.00, NULL, 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800', 'Tissu précieux satiné vert émeraude avec finitions haute couture et dentelle dorée aux poignets.', 'Fermeture invisible au dos, coupe sirène ajustée. Tailles disponibles : XS, S, M, L.', 1),
(4, 'Couronne Royale d\'Or & Cristaux', 'accessoires', 'Accessoire de Tête', 40000.00, NULL, 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=800', 'Diadème majestueux réhaussé de strass étincelants et de cristal taillé reflet ambre.', 'Peigne de maintien intégré, structure légère et confortable pour de longues cérémonies.', 0),
(5, 'Takchita Blanche & Broderies Argent', 'tenues', 'Tenue de Mariée', 110000.00, NULL, 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&q=80&w=800', 'Takchita 2 pièces en soie blanche de haute qualité avec ornements argentés perlés.', 'Broderie sfifa traditionnelle, traîne légère élégante. Tailles disponibles : S, M, XL.', 1),
(6, 'Ceinture Traditionnelle Ciselée', 'accessoires', 'Ceintures & Accessoires', 30000.00, NULL, 'https://images.unsplash.com/photo-1611591475281-8d283326c73f?auto=format&fit=crop&q=80&w=800', 'Ceinture métallique dorée sculptée aux motifs arabesques traditionnels.', 'Système de maillons ajustables (du 36 au 46). S\'adapte à tous les kaftans et robes.', 0),
(7, 'Ensemble Jabador Homme Prestige', 'hommes', 'Tenue Homme', 75000.00, NULL, 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800', 'Ensemble 3 pièces comprenant tunique brodée, pantalon assorti et cape en lin noble.', 'Coupe moderne ajustée, finitions faites main. Tailles disponibles : M, L, XL, XXL.', 0),
(8, 'Parure Saphir & Zirconium', 'bijoux', 'Bijoux & Parures', 50000.00, NULL, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800', 'Ensemble collier, bracelet et boucles ornés de pierres bleu saphir et zircons.', 'Livrées dans leur étui en velours scellé FAITH DECOR.', 0),
(9, 'Voile de Mariée Dentelle de Calais', 'accessoires', 'Voiles & Traînes', 35000.00, NULL, 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800', 'Longueur cathédrale (3 mètres) en tulle de soie bordé de fine dentelle raffinée.', 'Système de fixation transparent par peigne dissimulé.', 0),
(10, 'Caftan Velours Bordeaux Impérial', 'tenues', 'Tenue Traditionnelle', 90000.00, NULL, 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&q=80&w=800', 'Velours bordeaux profond avec cartouche de cristal et fil d\'or précieux.', 'Boutonnage artisanal \'Aakad\' tout le long de la tenue. Tailles disponibles : S, M, L.', 1),
(11, 'Pochette de Fête Sertie de Strass', 'accessoires', 'Sacs & Pochettes', 25000.00, NULL, 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&q=80&w=800', 'Mini minaudière rigide couverte de paillettes d\'or et fermoir bijoux.', 'Chaînette d\'épaule amovible incluse.', 0),
(12, 'Diadème & Collier Émeraude', 'bijoux', 'Bijoux & Parures', 60000.00, NULL, 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=800', 'Duo altière de cérémonie comprenant la couronne et le collier assorti.', 'Pièce maîtresse de notre collection prestige.', 1);
